/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerificarWhatsappRouteImport } from './routes/verificar.whatsapp'
import { Route as VerificarEmailRouteImport } from './routes/verificar.email'
import { Route as ResultadoProcessoRouteImport } from './routes/resultado.$processo'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIncompletosRouteImport } from './routes/admin.incompletos'
import { Route as AdminFunilRouteImport } from './routes/admin.funil'
import { Route as ResultadoCpfCpfRouteImport } from './routes/resultado.cpf.$cpf'
import { Route as ResultadoCnpjCnpjRouteImport } from './routes/resultado.cnpj.$cnpj'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerificarWhatsappRoute = VerificarWhatsappRouteImport.update({
  id: '/verificar/whatsapp',
  path: '/verificar/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar/email',
  path: '/verificar/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoProcessoRoute = ResultadoProcessoRouteImport.update({
  id: '/resultado/$processo',
  path: '/resultado/$processo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncompletosRoute = AdminIncompletosRouteImport.update({
  id: '/incompletos',
  path: '/incompletos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFunilRoute = AdminFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AdminRoute,
} as any)
const ResultadoCpfCpfRoute = ResultadoCpfCpfRouteImport.update({
  id: '/resultado/cpf/$cpf',
  path: '/resultado/cpf/$cpf',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoCnpjCnpjRoute = ResultadoCnpjCnpjRouteImport.update({
  id: '/resultado/cnpj/$cnpj',
  path: '/resultado/cnpj/$cnpj',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/demo': typeof DemoRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/incompletos': typeof AdminIncompletosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/resultado/$processo': typeof ResultadoProcessoRoute
  '/verificar/email': typeof VerificarEmailRoute
  '/verificar/whatsapp': typeof VerificarWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/resultado/cnpj/$cnpj': typeof ResultadoCnpjCnpjRoute
  '/resultado/cpf/$cpf': typeof ResultadoCpfCpfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/demo': typeof DemoRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/incompletos': typeof AdminIncompletosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/resultado/$processo': typeof ResultadoProcessoRoute
  '/verificar/email': typeof VerificarEmailRoute
  '/verificar/whatsapp': typeof VerificarWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/resultado/cnpj/$cnpj': typeof ResultadoCnpjCnpjRoute
  '/resultado/cpf/$cpf': typeof ResultadoCpfCpfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/demo': typeof DemoRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/funil': typeof AdminFunilRoute
  '/admin/incompletos': typeof AdminIncompletosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/resultado/$processo': typeof ResultadoProcessoRoute
  '/verificar/email': typeof VerificarEmailRoute
  '/verificar/whatsapp': typeof VerificarWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/resultado/cnpj/$cnpj': typeof ResultadoCnpjCnpjRoute
  '/resultado/cpf/$cpf': typeof ResultadoCpfCpfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/demo'
    | '/obrigado'
    | '/admin/funil'
    | '/admin/incompletos'
    | '/admin/leads'
    | '/admin/login'
    | '/resultado/$processo'
    | '/verificar/email'
    | '/verificar/whatsapp'
    | '/admin/'
    | '/resultado/cnpj/$cnpj'
    | '/resultado/cpf/$cpf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/demo'
    | '/obrigado'
    | '/admin/funil'
    | '/admin/incompletos'
    | '/admin/leads'
    | '/admin/login'
    | '/resultado/$processo'
    | '/verificar/email'
    | '/verificar/whatsapp'
    | '/admin'
    | '/resultado/cnpj/$cnpj'
    | '/resultado/cpf/$cpf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/demo'
    | '/obrigado'
    | '/admin/funil'
    | '/admin/incompletos'
    | '/admin/leads'
    | '/admin/login'
    | '/resultado/$processo'
    | '/verificar/email'
    | '/verificar/whatsapp'
    | '/admin/'
    | '/resultado/cnpj/$cnpj'
    | '/resultado/cpf/$cpf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  DemoRoute: typeof DemoRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ResultadoProcessoRoute: typeof ResultadoProcessoRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  VerificarWhatsappRoute: typeof VerificarWhatsappRoute
  ResultadoCnpjCnpjRoute: typeof ResultadoCnpjCnpjRoute
  ResultadoCpfCpfRoute: typeof ResultadoCpfCpfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verificar/whatsapp': {
      id: '/verificar/whatsapp'
      path: '/verificar/whatsapp'
      fullPath: '/verificar/whatsapp'
      preLoaderRoute: typeof VerificarWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/email': {
      id: '/verificar/email'
      path: '/verificar/email'
      fullPath: '/verificar/email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$processo': {
      id: '/resultado/$processo'
      path: '/resultado/$processo'
      fullPath: '/resultado/$processo'
      preLoaderRoute: typeof ResultadoProcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incompletos': {
      id: '/admin/incompletos'
      path: '/incompletos'
      fullPath: '/admin/incompletos'
      preLoaderRoute: typeof AdminIncompletosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funil': {
      id: '/admin/funil'
      path: '/funil'
      fullPath: '/admin/funil'
      preLoaderRoute: typeof AdminFunilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resultado/cpf/$cpf': {
      id: '/resultado/cpf/$cpf'
      path: '/resultado/cpf/$cpf'
      fullPath: '/resultado/cpf/$cpf'
      preLoaderRoute: typeof ResultadoCpfCpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/cnpj/$cnpj': {
      id: '/resultado/cnpj/$cnpj'
      path: '/resultado/cnpj/$cnpj'
      fullPath: '/resultado/cnpj/$cnpj'
      preLoaderRoute: typeof ResultadoCnpjCnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminFunilRoute: typeof AdminFunilRoute
  AdminIncompletosRoute: typeof AdminIncompletosRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFunilRoute: AdminFunilRoute,
  AdminIncompletosRoute: AdminIncompletosRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  DemoRoute: DemoRoute,
  ObrigadoRoute: ObrigadoRoute,
  ResultadoProcessoRoute: ResultadoProcessoRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  VerificarWhatsappRoute: VerificarWhatsappRoute,
  ResultadoCnpjCnpjRoute: ResultadoCnpjCnpjRoute,
  ResultadoCpfCpfRoute: ResultadoCpfCpfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
